import { FormEvent, useMemo, useState } from 'react';
import { BarChart3, BedDouble, Building2, Check, Download, Plus, Printer, Settings, ShieldCheck, Stethoscope, Trash2, UserPlus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Badge, Button, EmptyState, Field, FormActions, Modal, PageHeader, Panel } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useHospital } from '../context/HospitalContext';
import { useI18n } from '../i18n';
import { useUi } from '../context/UiContext';
import { downloadXlsx } from '../utils/exportXlsx';
import { canEditVisitFees, hasPermission } from '../utils/permissions';
import type { Theme } from '../types';
import { printCurrentView } from '../utils/printDocument';

function DoctorModal({onClose}:{onClose:()=>void}){const {t,language}=useI18n();const {clinics,addDoctor}=useHospital();const {toast}=useUi();const [saving,setSaving]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const staffId=String(d.get('staffId')).trim(),password=String(d.get('password')),name=String(d.get('name')).trim(),selectedClinics=d.getAll('clinics').map(String);if(!staffId||!password||!name||!selectedClinics.length){toast(t('required'),'warn');return;}setSaving(true);try{await addDoctor({staffId,password,name,phone:String(d.get('phone')),scheduleText:String(d.get('scheduleText')||''),clinics:selectedClinics});toast(t('doctorSaved'));onClose()}catch(reason){toast(reason instanceof Error?reason.message:t('saveFailed'),'warn')}finally{setSaving(false)}};return <Modal title={<><UserPlus/>{t('addDoctor')}</>} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label={t('doctorName')} span={2}><input name="name" required disabled={saving}/></Field><Field label={t('phone')}><input name="phone" dir="ltr" disabled={saving}/></Field><Field label={t('doctorId')}><input name="staffId" required autoComplete="off" disabled={saving}/></Field><Field label={t('password')}><input name="password" type="password" minLength={8} required autoComplete="new-password" disabled={saving}/></Field><Field label="المواعيد / أيام الدوام" span={3}><textarea name="scheduleText" placeholder="مثال: السبت صباحاً، الاثنين مساءً..." disabled={saving}/></Field><Field label={t('assignedClinics')} span={3}><select name="clinics" multiple size={7} required disabled={saving}>{clinics.filter(c=>c.active).map(c=><option value={c.id} key={c.id}>{language==='ar'?c.nameAr:c.nameEn}</option>)}</select></Field></div><div className="privacy-banner"><ShieldCheck/><span>{t('doctorCredentialHint')}</span></div><FormActions><Button className="btn-primary" type="submit" disabled={saving}><Check/>{t('save')}</Button></FormActions></form></Modal>}

export function DoctorsPage(){const {t,language}=useI18n();const {user}=useAuth();const {doctors,clinicName,removeDoctor}=useHospital();const {toast}=useUi();const [modal,setModal]=useState(false);const canCreate=hasPermission(user,'doctors.create');const canDelete=hasPermission(user,'doctors.delete');const activeDoctors=doctors.filter(doctor=>doctor.active);return <><PageHeader crumb={t('staff')} title={t('doctorsTitle')} sub={`${t('totalCount')}: ${activeDoctors.length}`} actions={canCreate?<Button className="btn-primary" onClick={()=>setModal(true)}><Plus/>{t('addDoctor')}</Button>:undefined}/>{activeDoctors.length?<div className="doctor-grid">{activeDoctors.map(doctor=><article className="doctor-card glass" key={doctor.id}><div className="clinic-icon"><Stethoscope/></div><h3>{doctor.name}</h3><p>{doctor.clinics.map(id=>clinicName(id,language)).join(' · ')||'—'}</p>{doctor.scheduleText&&<small className="doctor-schedule-text">{doctor.scheduleText}</small>}<Badge>{doctor.staffId}</Badge>{canDelete&&<Button className="btn-danger btn-sm clinic-remove" onClick={()=>{if(confirm(t('confirmRemoveDoctor'))){void removeDoctor(doctor.id).then(()=>toast(t('doctorRemoved'))).catch(reason=>toast(reason instanceof Error?reason.message:t('saveFailed'),'warn'))}}}><Trash2/>{t('remove')}</Button>}</article>)}</div>:<Panel><EmptyState title={t('noDoctors')} sub={t('noDoctorsSub')}/></Panel>}{modal&&canCreate&&<DoctorModal onClose={()=>setModal(false)}/>}</>}

function ClinicModal({onClose,canEditFee}:{onClose:()=>void;canEditFee:boolean}){
  const {t}=useI18n();const {addClinic}=useHospital();const {toast}=useUi();const [kind,setKind]=useState<'outpatient'|'inpatient'|'mixed'>('outpatient');
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const fee=Number(d.get('fee')||0);const dailyRate=Number(d.get('dailyRate')||0);try{await addClinic({nameAr:String(d.get('nameAr')),nameEn:String(d.get('nameEn')),code:String(d.get('code')||''),visitFee:kind==='inpatient'?0:fee,kind,dailyRate:kind==='outpatient'?undefined:dailyRate});toast('تمت إضافة القسم للمستشفى');onClose()}catch(reason){toast(reason instanceof Error?reason.message:t('saveFailed'),'warn')}};
  return <Modal title={<><Building2/>إضافة قسم / عيادة</>} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label={t('clinicNameAr')}><input name="nameAr" required/></Field><Field label={t('clinicNameEn')}><input name="nameEn" required dir="ltr"/></Field><Field label="رمز العيادة"><input name="code" dir="ltr" maxLength={6} placeholder="مثال ENT" required/></Field><Field label="نوع القسم"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="outpatient">عيادة خارجية</option><option value="inpatient">قسم مبيت</option><option value="mixed">قسم مختلط</option></select></Field>{canEditFee?<> {kind!=='inpatient'&&<Field label={t('standardVisitFee')}><input name="fee" type="number" min="0" defaultValue="0" required/></Field>}{kind!=='outpatient'&&<Field label="التكلفة اليومية للمبيت"><input name="dailyRate" type="number" min="0" defaultValue="0"/></Field>}</>:<><input type="hidden" name="fee" value="0"/><input type="hidden" name="dailyRate" value="0"/></>}</div><p className="form-hint">قسم المبيت سيظهر مباشرة في شاشة المبيت ويمكن اختيار المريض وإدخاله إليه. الرسوم المالية تبقى محمية بصلاحيات الصندوق.</p><FormActions><Button className="btn-primary" type="submit"><Check/>{t('save')}</Button></FormActions></form></Modal>
}

export function ClinicsPage(){
  const {t,language}=useI18n();const {user}=useAuth();const {clinics,doctors,visits,removeClinic,updateClinicFee}=useHospital();const {toast}=useUi();const [modal,setModal]=useState(false);const [editing,setEditing]=useState('');const canCreate=hasPermission(user,'clinics.create');const canDelete=hasPermission(user,'clinics.delete');const canEditFee=canEditVisitFees(user);
  return <><PageHeader crumb={t('organizational')} title="أقسام وعيادات المستشفى" sub={`الأقسام والعيادات المتاحة: ${clinics.filter(c=>c.active).length}`} actions={canCreate?<Button className="btn-primary" onClick={()=>setModal(true)}><Plus/>إضافة قسم / عيادة</Button>:undefined}/><div className="doctor-grid clinics-grid">{clinics.filter(c=>c.active).map(clinic=><article className="doctor-card glass" key={clinic.id}><div className="clinic-icon">{clinic.kind==='inpatient'?<BedDouble/>:<Building2/>}</div><h3>{language==='ar'?clinic.nameAr:clinic.nameEn}</h3><Badge color="violet">{clinic.code||'CLN'}</Badge><p>{clinic.kind==='inpatient'?'قسم مبيت':clinic.kind==='mixed'?'عيادات + مبيت':`${doctors.filter(d=>d.clinics.includes(clinic.id)).length} ${t('doctorCount')} · ${visits.filter(v=>v.clinicId===clinic.id).length} ${t('visitCount')}`}</p><Badge color={clinic.kind==='inpatient'?'violet':clinic.kind==='mixed'?'amber':'cyan'}>{clinic.kind==='inpatient'?'مبيت':clinic.kind==='mixed'?'مختلط':'عيادة خارجية'}</Badge>{canEditFee&&<div className="clinic-fee-row"><span>{clinic.kind==='inpatient'?'التكلفة اليومية':t('standardVisitFee')}</span>{clinic.kind!=='inpatient'&&editing===clinic.id?<input type="number" defaultValue={clinic.visitFee} autoFocus onBlur={e=>{const value=Number(e.target.value);setEditing('');void updateClinicFee(clinic.id,value).then(()=>toast(t('feeUpdated'))).catch(reason=>toast(reason instanceof Error?reason.message:t('saveFailed'),'warn'))}}/>:<button onClick={()=>clinic.kind!=='inpatient'&&setEditing(clinic.id)} disabled={clinic.kind==='inpatient'}>{(clinic.kind==='inpatient'?(clinic.dailyRate||0):clinic.visitFee).toFixed(2)} ₪</button>}</div>}{canDelete&&clinic.key!=='inpatient'&&<Button className="btn-danger btn-sm clinic-remove" onClick={()=>{if(confirm(t('confirmRemoveClinic'))){void removeClinic(clinic.id).then(()=>toast(t('clinicRemoved'))).catch(reason=>toast(reason instanceof Error?reason.message:t('saveFailed'),'warn'))}}}><Trash2/>{t('remove')}</Button>}</article>)}</div>{modal&&canCreate&&<ClinicModal canEditFee={canEditFee} onClose={()=>setModal(false)}/>}</>
}

function SponsorModal({onClose}:{onClose:()=>void}){const {t}=useI18n();const {addSponsor}=useHospital();const {toast}=useUi();const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);addSponsor(String(d.get('nameAr')),String(d.get('nameEn')));toast(t('sponsorAdded'));onClose()};return <Modal title={<><Plus/>{t('addSponsor')}</>} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label={t('sponsorNameAr')}><input name="nameAr" required/></Field><Field label={t('sponsorNameEn')}><input name="nameEn" required dir="ltr"/></Field></div><FormActions><Button className="btn-primary" type="submit"><Check/>{t('save')}</Button></FormActions></form></Modal>}

type ColumnKey='name'|'age'|'nationalId'|'dob'|'gender'|'clinicType'|'doctorName';
const reportColumnKeys:ColumnKey[]=['name','age','nationalId','dob','gender','clinicType','doctorName'];

export function ReportsPage(){
  const {t,language}=useI18n();
  const {user}=useAuth();
  const {patients,sponsors,visits,clinics,doctors}=useHospital();
  const {toast}=useUi();
  const [columns,setColumns]=useState<ColumnKey[]>(['name','age','nationalId','dob']);
  const [minAge,setMinAge]=useState(5);const [maxAge,setMaxAge]=useState(20);
  const [sponsor,setSponsor]=useState('');const [gender,setGender]=useState('');const [clinicId,setClinicId]=useState('');const [doctorId,setDoctorId]=useState('');
  const [sponsorModal,setSponsorModal]=useState(false);
  const canManageSponsors=hasPermission(user,'sponsors.manage');const canExport=hasPermission(user,'reports.export');const canPrint=hasPermission(user,'reports.print');
  const age=(dob:string)=>{if(!dob)return 0;const birth=new Date(dob),now=new Date();let value=now.getFullYear()-birth.getFullYear();if(now<new Date(now.getFullYear(),birth.getMonth(),birth.getDate()))value--;return value};
  const filtered=useMemo(()=>patients.filter(p=>{const a=age(p.dob);const matchingVisit=!clinicId&&!doctorId||visits.some(visit=>visit.patientId===p.id&&(!clinicId||visit.clinicId===clinicId)&&(!doctorId||visit.doctorId===doctorId));return a>=minAge&&a<=maxAge&&(!sponsor||p.coverageEntity===sponsor)&&(!gender||p.gender===gender)&&matchingVisit}),[patients,visits,minAge,maxAge,sponsor,gender,clinicId,doctorId]);
  const labels:Record<ColumnKey,string>={name:t('fullName'),age:t('age'),nationalId:t('idNumber'),dob:t('dob'),gender:t('gender'),clinicType:t('clinicType'),doctorName:t('doctorName')};
  const checkboxLabels:Record<ColumnKey,string>={name:t('showName'),age:t('showAge'),nationalId:t('showNationalId'),dob:t('showDob'),gender:t('showGender'),clinicType:t('showClinicType'),doctorName:t('showDoctorName')};
  const matchingVisits=(patientId:string)=>visits.filter(visit=>visit.patientId===patientId&&(!clinicId||visit.clinicId===clinicId)&&(!doctorId||visit.doctorId===doctorId));
  const cellValue=(patient:(typeof patients)[number],key:ColumnKey):string|number=>{
    if(key==='name')return patient.fullName;if(key==='age')return age(patient.dob);if(key==='nationalId')return patient.idNumber;if(key==='dob')return patient.dob;if(key==='gender')return t(patient.gender);
    const patientVisits=matchingVisits(patient.id);
    if(key==='clinicType')return [...new Set(patientVisits.map(visit=>{const clinic=clinics.find(item=>item.id===visit.clinicId);return clinic?(language==='ar'?clinic.nameAr:clinic.nameEn):''}).filter(Boolean))].join('، ')||'—';
    return [...new Set(patientVisits.map(visit=>doctors.find(item=>item.id===visit.doctorId)?.name||'').filter(Boolean))].join('، ')||'—';
  };
  const toggle=(key:ColumnKey)=>setColumns(current=>current.includes(key)?current.filter(column=>column!==key):[...current,key]);
  const row=(patient:(typeof patients)[number])=>columns.map(key=>cellValue(patient,key));
  const exportExcel=async()=>{await downloadXlsx(`wafaa-patients-${new Date().toISOString().slice(0,10)}.xlsx`,columns.map(key=>labels[key]),filtered.map(row),language==='ar');toast(t('excelGenerated'))};
  return <>
    <PageHeader crumb={t('queries')} title={t('reportsTitle')} sub={t('reportsSub')} actions={canManageSponsors?<Button className="btn-ghost" onClick={()=>setSponsorModal(true)}><Plus/>{t('addSponsor')}</Button>:undefined}/>
    <div className="reports-layout"><Panel>
      <div className="panel-head"><h3><BarChart3/>{t('reportBuilder')}</h3></div>
      <div className="report-section"><b>{t('outputColumns')}</b><div className="checkbox-grid">{reportColumnKeys.map(key=><label key={key}><input type="checkbox" checked={columns.includes(key)} onChange={()=>toggle(key)}/><span>{checkboxLabels[key]}</span></label>)}</div></div>
      <div className="report-section"><b>{t('ageRange')}</b><div className="dual-range"><label>{t('fromAge')}<input type="number" min="0" max={maxAge} value={minAge} onChange={e=>setMinAge(Number(e.target.value))}/></label><span>{minAge} — {maxAge}</span><label>{t('toAge')}<input type="number" min={minAge} max="120" value={maxAge} onChange={e=>setMaxAge(Number(e.target.value))}/></label></div></div>
      <div className="report-section report-filter-grid"><Field label={`${t('coverage')} (${t('optional')})`}><select value={sponsor} onChange={e=>setSponsor(e.target.value)}><option value="">{t('all')}</option>{sponsors.map(item=><option value={item.id} key={item.id}>{language==='ar'?item.nameAr:item.nameEn}</option>)}</select></Field><Field label={`${t('gender')} (${t('optional')})`}><select value={gender} onChange={e=>setGender(e.target.value)}><option value="">{t('all')}</option><option value="male">{t('male')}</option><option value="female">{t('female')}</option></select></Field><Field label={`${t('clinicType')} (${t('optional')})`}><select value={clinicId} onChange={e=>{const nextClinic=e.target.value;setClinicId(nextClinic);if(nextClinic&&doctorId&&!doctors.find(item=>item.id===doctorId)?.clinics.includes(nextClinic))setDoctorId('')}}><option value="">{t('all')}</option>{clinics.filter(item=>item.active).map(item=><option value={item.id} key={item.id}>{language==='ar'?item.nameAr:item.nameEn}</option>)}</select></Field><Field label={`${t('doctorName')} (${t('optional')})`}><select value={doctorId} onChange={e=>setDoctorId(e.target.value)}><option value="">{t('all')}</option>{doctors.filter(item=>item.active&&(!clinicId||item.clinics.includes(clinicId))).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></Field></div>
      <FormActions>{canExport&&<Button className="btn-primary" onClick={exportExcel} disabled={!columns.length}><Download/>{t('generateExcel')}</Button>}{canPrint&&<Button className="btn-ghost" onClick={()=>void printCurrentView()}><Printer/>{t('printReport')}</Button>}</FormActions>
    </Panel><Panel className="report-preview"><div className="panel-head"><h3>{t('reportPreview')}</h3><Badge color="emerald">{filtered.length}</Badge></div>{filtered.length?<div className="table-wrap"><table><thead><tr>{columns.map(key=><th key={key}>{labels[key]}</th>)}</tr></thead><tbody>{filtered.map(patient=><tr key={patient.id}>{columns.map(key=><td key={key}>{cellValue(patient,key)}</td>)}</tr>)}</tbody></table></div>:<EmptyState title={t('noReportResults')} sub={t('adjustFilters')}/>}</Panel></div>
    {sponsorModal&&canManageSponsors&&<SponsorModal onClose={()=>setSponsorModal(false)}/>} 
  </>;
}

export function SettingsPage(){
  const {t,language,setLanguage}=useI18n();
  const {user}=useAuth();
  const {theme,setTheme,toast}=useUi();
  const {resetAll}=useHospital();
  const canReset=hasPermission(user,'settings.update');
  const clear=()=>{if(confirm(t('confirmClear'))){resetAll();toast(t('cleared'))}};
  const themes:{key:Theme;name:string;hint:string}[]=[
    {key:'dark',name:language==='ar'?'الوضع الليلي':'Night mode',hint:language==='ar'?'داكن ومريح للمناوبات':'Dark and calm for shifts'},
    {key:'light',name:language==='ar'?'الوضع النهاري':'Day mode',hint:language==='ar'?'فاتح وواضح في الإضاءة العالية':'Bright and clear in daylight'},
    {key:'aurora',name:language==='ar'?'وضع الشفق':'Aurora mode',hint:language==='ar'?'ألوان جذابة مع تباين عالٍ':'Vibrant colors with high contrast'},
    {key:'pearl',name:language==='ar'?'وضع اللؤلؤ':'Pearl mode',hint:language==='ar'?'إضاءة ناعمة بلون لؤلؤي وتباين واضح':'Soft pearl lighting with crisp contrast'},
  ];
  return <><PageHeader crumb={t('system')} title={t('settingsTitle')} sub={t('settingsSub')}/><Panel className="settings-panel"><div className="settings-row settings-theme-row"><div><b>{language==='ar'?'وضع العرض':'Interface theme'}</b><span>{language==='ar'?'اختر الوضع المناسب، وسيبقى الكلام والقوائم واضحة في كل الأقسام.':'Choose a theme; text and lists remain readable across all modules.'}</span></div><div className="theme-choice-grid">{themes.map(item=><button key={item.key} type="button" className={`theme-choice ${theme===item.key?'active':''} theme-choice-${item.key}`} onClick={()=>setTheme(item.key)}><i/><span><b>{item.name}</b><small>{item.hint}</small></span></button>)}</div></div><div className="settings-row"><div><b>{t('language')}</b><span>{t('languageSub')}</span></div><button className="language-choice" onClick={()=>setLanguage(language==='ar'?'en':'ar')}>{language==='ar'?'English':'العربية'}</button></div><div className="settings-row"><div><b>{t('laravelReady')}</b><span>{t('laravelReadySub')}</span></div><Badge color="emerald">API v1</Badge></div>{canReset&&<div className="settings-row"><div><b>{t('clearData')}</b><span>{t('clearDataSub')}</span></div><Button className="btn-danger btn-sm" onClick={clear}><Trash2/>{t('clear')}</Button></div>}</Panel></>}
export function NotFoundPage(){const navigate=useNavigate();const {t}=useI18n();return <Panel><EmptyState title="404" sub={t('noActivitySub')} action={<Button className="btn-primary" onClick={()=>navigate('/')}>{t('dashboard')}</Button>}/></Panel>}
