import { FormEvent, useState } from 'react';
import { Check, CircleDollarSign, Plus, Smartphone, WalletCards } from 'lucide-react';
import { Badge, Button, EmptyState, Field, FormActions, Modal, PageHeader, Panel } from '../components/ui';
import { useHospital } from '../context/HospitalContext';
import { useI18n } from '../i18n';
import { useUi } from '../context/UiContext';
import type { TransferDetails } from '../types';
import { useAuth } from '../context/AuthContext';

function InvoiceModal({onClose}:{onClose:()=>void}){
  const {t}=useI18n();const {patients,addInvoice}=useHospital();const {toast}=useUi();const [method,setMethod]=useState<'cash'|'app'>('cash');
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const d=new FormData(event.currentTarget);const patientId=String(d.get('patient')||'');if(!patientId){toast(t('selectPatient'),'warn');return;}let transferDetails:TransferDetails|undefined;if(method==='app'){const senderPhone=String(d.get('senderPhone')||''),senderName=String(d.get('senderName')||'');if(!senderPhone||!senderName){toast(t('transferFieldsRequired'),'warn');return;}transferDetails={senderPhone,senderName,source:String(d.get('source')) as TransferDetails['source']};}const invoice=addInvoice({patientId,service:String(d.get('service')),unitPrice:Number(d.get('unitPrice')),coveragePct:Number(d.get('coverage')),paymentMethod:method,transferDetails});toast(`${t('invoiceSaved')} — ${invoice.payableAmount.toFixed(2)} ₪`);onClose()};
  return <Modal title={<><CircleDollarSign/>{t('newInvoice')}</>} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label={t('patientName')} span={3}><select name="patient" required><option value="">—</option>{patients.map(p=><option value={p.id} key={p.id}>{p.fullName}</option>)}</select></Field><Field label={t('service')} span={2}><input name="service" required/></Field><Field label={t('unitPrice')}><input name="unitPrice" type="number" min="0" step="0.01" required/></Field><Field label={t('coverageRatio')}><input name="coverage" type="number" min="0" max="100" defaultValue="0"/></Field><Field label={t('paymentMethod')} span={2}><div className="payment-toggle"><button type="button" className={method==='cash'?'active':''} onClick={()=>setMethod('cash')}><CircleDollarSign/>{t('cash')}</button><button type="button" className={method==='app'?'active':''} onClick={()=>setMethod('app')}><Smartphone/>{t('appTransfer')}</button></div></Field>{method==='app'&&<><Field label={t('senderPhone')}><input name="senderPhone" dir="ltr"/></Field><Field label={t('senderName')}><input name="senderName"/></Field><Field label={t('transferSource')}><select name="source"><option value="wallet">{t('wallet')}</option><option value="bank">{t('bank')}</option><option value="jawwalPay">{t('jawwalPay')}</option></select></Field></>}</div><div className="invoice-note glass"><WalletCards/><span>{t('invoiceWalletHint')}</span></div><FormActions><Button className="btn-primary" type="submit"><Check/>{t('saveInvoice')}</Button><Button className="btn-ghost" type="button" onClick={onClose}>{t('cancel')}</Button></FormActions></form></Modal>
}

export function BillingPage(){
  const {t,language}=useI18n();const {user}=useAuth();const {patients,invoices,patientName}=useHospital();const [modal,setModal]=useState(false);
  const canCreate=user?.permissions.includes('billing.create')??false;
  const canViewAll=user?.permissions.includes('billing.view')??false;
  const visibleInvoices=canViewAll?invoices:invoices.filter(item=>item.paymentMethod==='cash');
  const total=visibleInvoices.reduce((sum,item)=>sum+item.payableAmount,0);
  return <><PageHeader crumb={t('accounts')} title={t('billingTitle')} sub={`${t('walletCredits')}: ${total.toFixed(2)} ₪`} actions={canCreate?<Button className="btn-primary" disabled={!patients.length} onClick={()=>setModal(true)}><Plus/>{t('newInvoice')}</Button>:undefined}/><Panel><div className="panel-head"><h3><CircleDollarSign/>{t('invoiceRecord')}</h3><Badge color="emerald">{visibleInvoices.length}</Badge></div>{visibleInvoices.length?<div className="table-wrap"><table><thead><tr><th>{t('receipt')}</th><th>{t('patientName')}</th><th>{t('service')}</th><th>{t('unitPrice')}</th><th>{t('coverageRatio')}</th><th>{t('paid')}</th><th>{t('paymentMethod')}</th><th>{t('date')}</th></tr></thead><tbody>{visibleInvoices.slice().reverse().map(item=><tr key={item.id}><td><Badge color="violet">{item.receiptNumber}</Badge></td><td><b>{patientName(item.patientId)}</b></td><td>{item.service}</td><td>{item.unitPrice.toFixed(2)} ₪</td><td>{item.coveragePct}%</td><td className="green">{item.payableAmount.toFixed(2)} ₪</td><td>{item.paymentMethod==='cash'?t('cash'):`${t('appTransfer')} · ${t(item.transferDetails?.source||'app')}`}</td><td>{new Date(item.date).toLocaleString(language==='ar'?'ar-EG':'en-US')}</td></tr>)}</tbody></table></div>:<EmptyState title={t('noInvoices')} sub={t('noInvoicesSub')}/>}</Panel>{modal&&canCreate&&<InvoiceModal onClose={()=>setModal(false)}/>}</>;
}
