import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Check, FlaskConical, Image, Pencil, ScanLine, Settings2, WalletCards } from 'lucide-react';
import { Badge, Button, EmptyState, Field, FormActions, Modal, PageHeader, Panel } from '../components/ui';
import { DiagnosticCatalogPanel } from '../components/DiagnosticCatalog';
import { useAuth } from '../context/AuthContext';
import { useHospital } from '../context/HospitalContext';
import { useI18n } from '../i18n';
import { useUi } from '../context/UiContext';
import type { DiagnosticService, RadiologyOrder } from '../types';
import { canManageFinancialCatalog, canUseBilling, canViewPatientFinance } from '../utils/permissions';

function OrderModal({type,onClose}:{type:DiagnosticService['type'];onClose:()=>void}){
  const {t,language}=useI18n();const {toast}=useUi();const {user}=useAuth();const {patients,doctors,diagnosticServices,orderDiagnostic}=useHospital();
  const services=diagnosticServices.filter(item=>item.active&&item.type===type);const [patientId,setPatientId]=useState(patients[0]?.id||'');const [serviceId,setServiceId]=useState(services[0]?.id||'');
  const patient=patients.find(item=>item.id===patientId);const service=services.find(item=>item.id===serviceId);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const result=orderDiagnostic({patientId,serviceId,doctorId:String(data.get('doctor')||'')||undefined});if(!result.ok){toast(t(result.reason==='insufficient_balance'?'insufficientDiagnosticBalance':'selectDiagnosticService'),'warn');return;}toast(t('diagnosticOrderCreated'));onClose()};
  const financialVisible=canManageFinancialCatalog(user)||canUseBilling(user)||canViewPatientFinance(user);
  return <Modal title={<>{type==='lab'?<FlaskConical/>:<Image/>}{t(type==='lab'?'requestLab':'requestXray')}</>} onClose={onClose}>{financialVisible&&<div className="balance-check glass"><WalletCards/><span>{t('availableBalance')}<b>{patient?.walletBalance.toFixed(2)||'0.00'} ₪</b></span><span>{t('diagnosticFee')}<b>{service?.price.toFixed(2)||'0.00'} ₪</b></span></div>}<form onSubmit={submit}><div className="form-grid"><Field label={t('patient')} span={2}><select value={patientId} onChange={e=>setPatientId(e.target.value)} required><option value="">—</option>{patients.map(item=><option value={item.id} key={item.id}>{item.fullName} · {item.medicalSerial}</option>)}</select></Field><Field label={t('diagnosticService')} span={2}><select value={serviceId} onChange={e=>setServiceId(e.target.value)} required><option value="">—</option>{services.map(item=><option value={item.id} key={item.id}>{language==='ar'?item.nameAr:item.nameEn}{financialVisible?` · ${item.price.toFixed(2)} ₪`:''}</option>)}</select></Field><Field label={`${t('requestingDoctor')} (${t('optional')})`}><select name="doctor"><option value="">{t('externalOrNoDoctor')}</option>{doctors.filter(item=>item.active).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></Field>{financialVisible&&<Field label={t('servicePrice')}><input value={service?.price||0} readOnly className="readonly-input"/></Field>}</div>{financialVisible&&<p className="form-hint">{t('diagnosticWalletHint')}</p>}<FormActions><Button className="btn-primary" type="submit" disabled={!patientId||!serviceId}><Check/>{t('confirmDiagnosticOrder')}</Button><Button className="btn-ghost" type="button" onClick={onClose}>{t('cancel')}</Button></FormActions></form></Modal>
}

function RadiologyResultModal({order,onClose}:{order:RadiologyOrder;onClose:()=>void}){
  const {language}=useI18n();const {toast}=useUi();const {updateRadiologyOrder,patientName}=useHospital();const [status,setStatus]=useState<RadiologyOrder['status']>(order.status);const [result,setResult]=useState(order.result||'');
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();updateRadiologyOrder(order.id,{status,result:result.trim(),...(status==='done'?{completedAt:new Date().toISOString()}: {})});toast(language==='ar'?'تم تحديث طلب الأشعة وحفظ التقرير':'Radiology order updated');onClose()};
  return <Modal title={<><Image/>{language==='ar'?'تحديث طلب الأشعة / التقرير':'Update radiology order / report'}</>} onClose={onClose}><div className="radiology-order-banner"><b>{patientName(order.patientId)}</b><span>{order.exam} · {order.date}</span></div><form onSubmit={submit}><div className="form-grid"><Field label={language==='ar'?'حالة الطلب':'Order status'}><select value={status} onChange={e=>setStatus(e.target.value as RadiologyOrder['status'])}><option value="waiting">{language==='ar'?'بانتظار التصوير':'Waiting'}</option><option value="done">{language==='ar'?'مكتمل':'Completed'}</option></select></Field><Field label={language==='ar'?'نتيجة / تقرير الأشعة':'Radiology result / report'} span={3}><textarea rows={8} value={result} onChange={e=>setResult(e.target.value)} placeholder={language==='ar'?'اكتب وصف الأشعة، النتيجة والانطباع النهائي...':'Enter findings, result and impression...'}/></Field></div><FormActions><Button className="btn-primary" type="submit"><Check/>{language==='ar'?'حفظ التحديث':'Save update'}</Button><Button className="btn-ghost" type="button" onClick={onClose}>{language==='ar'?'إلغاء':'Cancel'}</Button></FormActions></form></Modal>
}

export function DiagnosticsPage(){
  const {t,language}=useI18n();const {can,user}=useAuth();const {diagnosticServices,labs,radiology,patientName,doctorName,refreshDiagnosticServices}=useHospital();
  const [tab,setTab]=useState<'lab'|'radiology'|'catalog'>('lab');const [orderType,setOrderType]=useState<DiagnosticService['type']|null>(null);const [editingRadiology,setEditingRadiology]=useState<RadiologyOrder|null>(null);
  useEffect(()=>{void refreshDiagnosticServices().catch(()=>undefined)},[refreshDiagnosticServices]);
  const canOrder=can('diagnostics.create');const canUpdate=can('diagnostics.update');const canCatalog=can('diagnostic_catalog.view')||can('diagnostic_catalog.create')||can('diagnostic_catalog.update')||can('diagnostic_catalog.delete')||canManageFinancialCatalog(user);const financialVisible=canManageFinancialCatalog(user)||canUseBilling(user)||canViewPatientFinance(user);const activeServices=useMemo(()=>diagnosticServices.filter(item=>item.active),[diagnosticServices]);
  const labServiceCount=activeServices.filter(x=>x.type==='lab').length;const radiologyServiceCount=activeServices.filter(x=>x.type==='radiology').length;
  return <><PageHeader crumb={t('diagnostics')} title={t('diagnosticsTitle')} sub={`${t('labRequests')}: ${labs.length} · ${t('xrayExams')}: ${radiology.length} · ${language==='ar'?'أنواع مفعلة':'active services'}: ${activeServices.length}`} actions={<>{canOrder&&<Button className="btn-ghost" onClick={()=>setOrderType('lab')}><FlaskConical/>{t('requestLab')}</Button>}{canOrder&&<Button className="btn-primary" onClick={()=>setOrderType('radiology')}><Image/>{t('requestXray')}</Button>}</>}/><div className="diagnostic-overview"><article className="glass"><FlaskConical/><div><span>{language==='ar'?'أنواع فحوصات مخبرية':'Lab test types'}</span><b>{labServiceCount}</b></div></article><article className="glass"><Image/><div><span>{language==='ar'?'أنواع أشعة':'Radiology types'}</span><b>{radiologyServiceCount}</b></div></article></div><div className="chip-row"><button className={`chip ${tab==='lab'?'active':''}`} onClick={()=>setTab('lab')}><FlaskConical/>{t('labRequests')}</button><button className={`chip ${tab==='radiology'?'active':''}`} onClick={()=>setTab('radiology')}><ScanLine/>{t('xrayExams')}</button>{canCatalog&&<button className={`chip ${tab==='catalog'?'active':''}`} onClick={()=>setTab('catalog')}><Settings2/>{t('diagnosticCatalog')}</button>}</div>
  {tab==='catalog'&&canCatalog?<Panel><DiagnosticCatalogPanel typeFilter="all"/></Panel>:<Panel>{tab==='lab'?(labs.length?<div className="table-wrap"><table><thead><tr><th>{t('patient')}</th><th>{t('diagnosticService')}</th><th>{t('requestingDoctor')}</th>{financialVisible&&<th>{t('diagnosticFee')}</th>}<th>{t('date')}</th><th>{t('status')}</th></tr></thead><tbody>{labs.slice().reverse().map(item=><tr key={item.id}><td><b>{patientName(item.patientId)}</b></td><td>{item.serviceName||t(item.category)}</td><td>{item.doctorId?doctorName(item.doctorId):t('notSpecified')}</td>{financialVisible&&<td><b>{(item.price||0).toFixed(2)} ₪</b></td>}<td>{item.date}</td><td><Badge color={item.status==='done'?'emerald':'amber'}>{t(item.status)}</Badge></td></tr>)}</tbody></table></div>:<EmptyState title={t('noLabs')} sub={t('noLabsSub')}/>):(radiology.length?<div className="table-wrap"><table><thead><tr><th>{t('patient')}</th><th>{t('examType')}</th><th>{t('requestingDoctor')}</th>{financialVisible&&<th>{t('diagnosticFee')}</th>}<th>{t('date')}</th><th>{t('status')}</th>{canUpdate&&<th>{language==='ar'?'الإجراء':'Action'}</th>}</tr></thead><tbody>{radiology.slice().reverse().map(item=><tr key={item.id}><td><b>{patientName(item.patientId)}</b></td><td><div className="radiology-exam-cell"><b>{item.exam}</b>{item.result&&<small>{item.result.slice(0,80)}{item.result.length>80?'…':''}</small>}</div></td><td>{item.doctorId?doctorName(item.doctorId):t('notSpecified')}</td>{financialVisible&&<td><b>{(item.price||0).toFixed(2)} ₪</b></td>}<td>{item.date}</td><td><Badge color={item.status==='done'?'emerald':'amber'}>{t(item.status)}</Badge></td>{canUpdate&&<td><Button className="btn-ghost btn-sm" onClick={()=>setEditingRadiology(item)}><Pencil/>{language==='ar'?'تحديث':'Update'}</Button></td>}</tr>)}</tbody></table></div>:<EmptyState title={t('noXrays')} sub={t('noXraysSub')}/>)}</Panel>}
  {orderType&&canOrder&&<OrderModal type={orderType} onClose={()=>setOrderType(null)}/>} {editingRadiology&&canUpdate&&<RadiologyResultModal order={editingRadiology} onClose={()=>setEditingRadiology(null)}/>}</>
}
