import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Check, Download, FlaskConical, Settings2, Plus, TestTube2, Trash2 } from 'lucide-react';
import { Badge, Button, EmptyState, Field, FormActions, Modal, PageHeader, Panel } from '../components/ui';
import { DiagnosticCatalogPanel } from '../components/DiagnosticCatalog';
import { useAuth } from '../context/AuthContext';
import { useHospital } from '../context/HospitalContext';
import { useI18n } from '../i18n';
import { useUi } from '../context/UiContext';
import type { LabOrder, LabResultRow } from '../types';
import { downloadLabReport } from '../utils/labReportPdf';
import { canManageFinancialCatalog } from '../utils/permissions';

function ResultsModal({order,onClose}:{order:LabOrder;onClose:()=>void}){
  const {t,language}=useI18n();const {toast}=useUi();const {patients,doctors,diagnosticServices,completeLabOrder}=useHospital();const service=diagnosticServices.find(item=>item.id===order.serviceId);const patient=patients.find(item=>item.id===order.patientId);
  const initial=order.resultRows?.length?order.resultRows:service?.tests.length?service.tests.map(item=>({...item,result:''})):[{test:order.serviceName||order.category,result:'',referenceRange:''}];
  const [rows,setRows]=useState<LabResultRow[]>(initial);const [notes,setNotes]=useState(order.notes||'');
  const setCell=(index:number,key:keyof LabResultRow,value:string)=>setRows(current=>current.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row));
  const submit=(event:FormEvent)=>{event.preventDefault();const valid=rows.filter(row=>row.test.trim()&&row.result.trim());if(!valid.length){toast(t('labResultRequired'),'warn');return;}const completed=completeLabOrder(order.id,valid,notes);if(completed&&patient){void downloadLabReport(completed,patient,order.doctorId?doctors.find(item=>item.id===order.doctorId)?.name||'—':t('notSpecified'),language);toast(t('labCompleted'));onClose()}};
  return <Modal title={<><TestTube2/>{t('enterLabResults')} — {patient?.fullName}</>} onClose={onClose}><div className="lab-order-summary glass"><span>{t('diagnosticService')}<b>{language==='ar'?service?.nameAr||order.serviceName:service?.nameEn||order.serviceName}</b></span><span>{t('idNumber')}<b>{patient?.idNumber}</b></span><span>{t('requestingDoctor')}<b>{order.doctorId?doctors.find(item=>item.id===order.doctorId)?.name:t('notSpecified')}</b></span></div><form onSubmit={submit}><div className="lab-result-editor"><div className="lab-result-head"><span>Test</span><span>Result</span><span>Reference Range</span><span/></div>{rows.map((row,index)=><div className="lab-result-row" key={index}><input value={row.test} onChange={e=>setCell(index,'test',e.target.value)} dir="ltr"/><input value={row.result} onChange={e=>setCell(index,'result',e.target.value)} required dir="ltr"/><input value={row.referenceRange} onChange={e=>setCell(index,'referenceRange',e.target.value)} dir="ltr"/><button type="button" onClick={()=>setRows(current=>current.filter((_,rowIndex)=>rowIndex!==index))}><Trash2/></button></div>)}</div><Button className="btn-ghost btn-sm" type="button" onClick={()=>setRows(current=>[...current,{test:'',result:'',referenceRange:''}])}><Plus/>{t('addTestRow')}</Button><Field label={t('notes')}><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><FormActions><Button className="btn-primary" type="submit"><Check/>{t('completeAndCreatePdf')}</Button><Button className="btn-ghost" type="button" onClick={onClose}>{t('cancel')}</Button></FormActions></form></Modal>
}

export function LaboratoryPage(){
  const {t,language}=useI18n();const {can,user}=useAuth();const {labs,patients,doctors,diagnosticServices,refreshDiagnosticServices}=useHospital();const [tab,setTab]=useState<'processing'|'done'|'catalog'>('processing');const [editing,setEditing]=useState<LabOrder|null>(null);const canComplete=can('laboratory.update');const canCatalog=can('diagnostic_catalog.view')||can('diagnostic_catalog.create')||can('diagnostic_catalog.update')||can('diagnostic_catalog.delete')||canManageFinancialCatalog(user);
  useEffect(()=>{void refreshDiagnosticServices().catch(()=>undefined)},[refreshDiagnosticServices]);
  const rows=useMemo(()=>tab==='catalog'?[]:labs.filter(item=>item.status===tab).slice().reverse(),[labs,tab]);const download=(order:LabOrder)=>{const patient=patients.find(item=>item.id===order.patientId);if(patient)void downloadLabReport(order,patient,order.doctorId?doctors.find(item=>item.id===order.doctorId)?.name||'—':t('notSpecified'),language)};
  const labTypes=diagnosticServices.filter(item=>item.active&&item.type==='lab').length;
  return <><PageHeader crumb={t('laboratory')} title={t('laboratoryPortal')} sub={`${t('processing')}: ${labs.filter(item=>item.status==='processing').length} · ${t('done')}: ${labs.filter(item=>item.status==='done').length} · ${language==='ar'?'أنواع الفحوصات':'test types'}: ${labTypes}`}/><div className="lab-kpis"><article className="glass"><FlaskConical/><div><span>{t('pendingAnalysis')}</span><b>{labs.filter(item=>item.status==='processing').length}</b></div></article><article className="glass"><Check/><div><span>{t('completedResults')}</span><b>{labs.filter(item=>item.status==='done').length}</b></div></article></div><div className="chip-row"><button className={`chip ${tab==='processing'?'active':''}`} onClick={()=>setTab('processing')}><TestTube2/>{t('processing')}</button><button className={`chip ${tab==='done'?'active':''}`} onClick={()=>setTab('done')}><Check/>{t('done')}</button>{canCatalog&&<button className={`chip ${tab==='catalog'?'active':''}`} onClick={()=>setTab('catalog')}><Settings2/>{language==='ar'?'إدارة الفحوصات والأسعار':'Tests & pricing'}</button>}</div>{tab==='catalog'&&canCatalog?<Panel><DiagnosticCatalogPanel typeFilter="lab"/></Panel>:<Panel>{rows.length?<div className="table-wrap"><table><thead><tr><th>{t('patient')}</th><th>{t('idNumber')}</th><th>{t('diagnosticService')}</th><th>{t('requestingDoctor')}</th><th>{t('date')}</th><th>{t('status')}</th><th/></tr></thead><tbody>{rows.map(order=>{const patient=patients.find(item=>item.id===order.patientId);const service=diagnosticServices.find(item=>item.id===order.serviceId);return <tr key={order.id}><td><b>{patient?.fullName||'—'}</b></td><td>{patient?.idNumber||'—'}</td><td>{language==='ar'?service?.nameAr||order.serviceName:service?.nameEn||order.serviceName}</td><td>{order.doctorId?doctors.find(item=>item.id===order.doctorId)?.name||'—':t('notSpecified')}</td><td>{order.date}</td><td><Badge color={order.status==='done'?'emerald':'amber'}>{t(order.status)}</Badge></td><td>{order.status==='processing'&&canComplete?<Button className="btn-primary btn-sm" onClick={()=>setEditing(order)}><TestTube2/>{t('enterResults')}</Button>:order.status==='done'?<Button className="btn-ghost btn-sm" onClick={()=>download(order)}><Download/>{t('downloadPdf')}</Button>:null}</td></tr>})}</tbody></table></div>:<EmptyState title={tab==='processing'?t('noPendingLabOrders'):t('noCompletedLabOrders')} sub={t('laboratoryQueueHint')}/>}</Panel>}{editing&&<ResultsModal order={editing} onClose={()=>setEditing(null)}/>}</>
}
