<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\{Invoice,Patient,WalletTransaction};
use Illuminate\Http\Request;
class ReportController extends Controller {
 public function patients(Request $q){$d=$q->validate(['columns'=>'nullable|array','columns.*'=>'in:name,age,nationalId,dob,gender,clinicType,doctorName','age_min'=>'nullable|integer|min:0|max:120','age_max'=>'nullable|integer|min:0|max:120','sponsor'=>'nullable|string','gender'=>'nullable|in:male,female','clinic_id'=>'nullable|uuid|exists:clinics,id','doctor_id'=>'nullable|uuid|exists:doctors,id']);$cols=$d['columns']??['name','age','nationalId','dob'];$query=Patient::with(['sponsor','visits.clinic','visits.doctor']);if(isset($d['age_min']))$query->whereDate('dob','<=',now()->subYears($d['age_min'])->toDateString());if(isset($d['age_max']))$query->whereDate('dob','>=',now()->subYears($d['age_max']+1)->addDay()->toDateString());$query->when($d['sponsor']??null,fn($x,$v)=>$x->whereHas('sponsor',fn($s)=>$s->where('id',$v)->orWhere('code',$v)))->when($d['gender']??null,fn($x,$v)=>$x->where('gender',$v))->when(($d['clinic_id']??null)||($d['doctor_id']??null),fn($x)=>$x->whereHas('visits',function($visits)use($d){$visits->when($d['clinic_id']??null,fn($v,$id)=>$v->where('clinic_id',$id))->when($d['doctor_id']??null,fn($v,$id)=>$v->where('doctor_id',$id));}));$rows=$query->get()->map(function($p)use($cols,$d){$patientVisits=$p->visits->filter(fn($visit)=>(!isset($d['clinic_id'])||$visit->clinic_id===$d['clinic_id'])&&(!isset($d['doctor_id'])||$visit->doctor_id===$d['doctor_id']));$all=['name'=>$p->full_name,'age'=>$p->dob->age,'nationalId'=>$p->id_number,'dob'=>$p->dob->format('Y-m-d'),'gender'=>$p->gender,'clinicType'=>$patientVisits->pluck('clinic.name_ar')->filter()->unique()->implode('، ')?:'—','doctorName'=>$patientVisits->pluck('doctor.name')->filter()->unique()->implode('، ')?:'—'];return collect($all)->only($cols);});return response()->json(['data'=>['columns'=>$cols,'rows'=>$rows]]);}
 public function finance(Request $q){$d=$q->validate(['from'=>'nullable|date','to'=>'nullable|date','method'=>'nullable|in:cash,app','patient_id'=>'nullable|uuid']);$query=Invoice::with('patient')->latest('issued_at');$query->when($d['from']??null,fn($x,$v)=>$x->whereDate('issued_at','>=',$v))->when($d['to']??null,fn($x,$v)=>$x->whereDate('issued_at','<=',$v))->when($d['method']??null,fn($x,$v)=>$x->where('payment_method',$v))->when($d['patient_id']??null,fn($x,$v)=>$x->where('patient_id',$v));$items=$query->get();return response()->json(['data'=>['summary'=>['count'=>$items->count(),'total'=>(float)$items->sum('payable_amount'),'cash'=>(float)$items->where('payment_method','cash')->sum('payable_amount'),'transfers'=>(float)$items->where('payment_method','app')->sum('payable_amount')],'rows'=>$items->map(fn($x)=>['receiptNumber'=>$x->receipt_number,'patientName'=>$x->patient->full_name,'service'=>$x->service,'amount'=>(float)$x->payable_amount,'method'=>$x->payment_method,'transferSource'=>$x->transfer_source,'senderName'=>$x->sender_name,'senderPhone'=>$x->sender_phone,'date'=>$x->issued_at->toISOString()])]]);}
}
