import { jsPDF } from 'jspdf';
import { printHtmlDocument } from './printDocument';
import { captureElementCanvas, cleanupExportArtifacts, createSilentExportFrame, downloadElementsAsDocx } from './documentDownload';
export interface FinancialDeclarationData{name:string;date:string;year:string;dailyAmount:string;totalAmount:string;age:string;stayDays:string}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
const logo=()=>`${window.location.origin}/wafaa-hospital-logo.png`;
export const financialDeclarationCss=`@page{size:A4 portrait;margin:0}.financial-declaration-doc{position:relative;box-sizing:border-box;width:794px;height:1123px;min-height:1123px;background:#fff!important;color:#050505!important;padding:38px 58px 34px;direction:rtl;font-family:Tahoma,"Segoe UI",Arial,sans-serif;line-height:2;box-shadow:none!important;transform:none!important;filter:none!important;text-shadow:none!important;overflow:hidden}.financial-declaration-doc *{box-sizing:border-box;text-shadow:none!important;filter:none!important}.financial-declaration-top{height:82px;position:relative;border-top:5px solid #35bad8;margin:17px 0 0}.financial-declaration-top img{position:absolute;right:0;top:-38px;width:84px;height:82px;object-fit:contain;background:#fff}.financial-declaration-date{display:block;text-align:left;direction:rtl;font-size:12px;font-weight:900;margin:0 0 4px;color:#000}.financial-declaration-doc h1{text-align:center;font-size:29px;margin:2px 0 15px;font-weight:900;line-height:1.4;color:#000}.financial-declaration-doc .intro{font-size:13px;font-weight:900;margin:0 0 4px;color:#000}.financial-declaration-doc .signer{font-size:13px;margin:1px 0;border-bottom:1px dotted #777;padding-bottom:1px;line-height:1.9;color:#000}.financial-declaration-doc .body{font-size:13px;text-align:justify;margin:15px 0 0;line-height:2.18;color:#000}.financial-declaration-doc .fill{font-weight:900;border-bottom:1px dotted #555;padding:0 7px;white-space:nowrap;color:#000}.financial-declaration-doc .fill.narrow{display:inline-block;min-width:46px;text-align:center}.financial-declaration-doc .closing{text-align:right;font-size:13px;font-weight:900;margin-top:9px;color:#000}.financial-declaration-signatures{display:grid;grid-template-columns:repeat(4,1fr);gap:28px;margin-top:18px;text-align:center;font-size:12px;font-weight:900;color:#000}.financial-declaration-signatures span{display:block;border-bottom:2px dotted #777;height:38px;margin-top:7px}.financial-declaration-footer{position:absolute;left:58px;right:58px;bottom:34px;border-top:5px solid #35bad8;padding-top:7px;display:grid;grid-template-columns:1.3fr 1fr 1fr 1.7fr;gap:8px;font-size:7.4px;direction:ltr;text-align:center;color:#333}.financial-declaration-footer b{font-size:8px}@media print{html,body{width:210mm;min-height:297mm;background:#fff!important}.financial-declaration-doc{width:210mm!important;height:297mm!important;min-height:297mm!important;padding:10mm 15mm 9mm!important;page-break-after:avoid;break-after:avoid}.financial-declaration-footer{left:15mm;right:15mm;bottom:9mm}}`;
export function financialDeclarationMarkup(data:FinancialDeclarationData){
  const d=data.date?data.date.replace(/-/g,'/'):'';
  const age=esc(data.age||'0000');
  const stay=esc(data.stayDays||'000');
  return `<article class="financial-declaration-doc"><div class="financial-declaration-top"><img src="${logo()}" alt="Wafaa Hospital"></div><div class="financial-declaration-date">التاريخ: ${esc(d)}</div><h1>سند إقرار والتزام</h1><p class="intro">نحن الموقعين أدناه:</p><p class="signer">1. الاسم: ............................................................... &nbsp; رقم هوية: ....................................</p><p class="signer">2. الاسم: ............................................................... &nbsp; رقم هوية: ....................................</p><div class="body">نقر ونعترف وبدون ضغط أو إكراه من أحد مادي أو معنوي وبالأهلية الشرعية المعتبرة شرعا وقانونا بأننا نلتزم ونتعهد متكافلين متضامنين مجتمعين أو منفردين بموجب هذا السند بدفع كافة المصاريف والنفقات والتكاليف الطبية والعلاجية والمكوث في مستشفى الوفاء والتي تستحق في ذمتنا لصالح مستشفى الوفاء للتأهيل الطبي بالغ ما بلغت ونلتزم ونتعهد بدفع أية مصاريف وذلك لعلاج المريض/ة <span class="fill">${esc(data.name||'........................................')}</span> والبالغ/ة من العمر (<span class="fill narrow">${age}</span> سنة)، وقد قمنا بدفع مبلغ وقدره (<span class="fill">${esc(data.totalAmount||'0')}</span> شيكل) لعلاج المريض/ة لمدة <span class="fill narrow">${stay}</span> أيام ابتداء من تاريخ <span class="fill">${esc(d)}</span> من سنة <span class="fill">${esc(data.year)}</span> بدفع مبلغ وقدره (<span class="fill">${esc(data.dailyAmount||'0')}</span> شيكل) عن كل ليلة مبيت في المستشفى.<br/><br/>كما ونتعهد بدفع كافة الرسوم والمصاريف التي قد تترصد في ذمتنا عندما تطلب المستشفى.<br/>ونتكفل بموجب هذا السند بأن نقوم بدفع ما التزمنا به من مبالغ وفي حالة تخلفنا أو تأخرنا عن الدفع فإنه يحق لمستشفى الوفاء للتأهيل الطبي اتخاذ كافة الإجراءات القانونية لتحصيل حقوقها ويحق لها الرجوع علينا مجتمعين أو منفردين متكافلين متضامنين ونقر بأن هذا السند يخضع لأحكام قانون التنفيذ 23/2005 ولمحكمة بداية غزة باعتباره سند تنفيذي دون حاجة لإخطار أو إنذار وفقا لنظام الحاسب الآلي لمشفى الوفاء.<br/>ونقر بأننا مسئولين عن هذا الإقرار والالتزام مسؤولية كاملة أمام كافة الجهات الرسمية والقضائية والعرفية وعليه فإننا نوقع على هذا السند بكل حرية واختيار وبإرادة حرة خالية من أي من عيوب من الإرادة.</div><div class="closing">حرر بتاريخ ${esc(d)}<br/>والله خير الشاهدين،</div><div class="financial-declaration-signatures"><div>توقيع الملتزم<span></span></div><div>توقيع الملتزم<span></span></div><div>شاهد أول<span></span></div><div>شاهد ثاني<span></span></div></div><div class="financial-declaration-footer"><span><b>P.O.Box:1051</b></span><span>1700 125 12</span><span>admin@elwafa.ps<br/>www.elwafa.ps</span><span>Abu Khadra Medical Complex - Gaza - Palestine<br/>مجمع أبو خضرة الطبي - غزة - فلسطين</span></div></article>`;
}
async function embedded(data:FinancialDeclarationData){let m=financialDeclarationMarkup(data);try{const blob=await (await fetch('/wafaa-hospital-logo.png')).blob();const uri=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(blob)});m=m.replace(logo(),uri)}catch{}return m}
async function host(data:FinancialDeclarationData){return createSilentExportFrame(`<style>${financialDeclarationCss}</style>${financialDeclarationMarkup(data)}`,794,1220)}
export async function downloadFinancialDeclarationPdf(data:FinancialDeclarationData){const h=await host(data);try{const page=h.querySelector('.financial-declaration-doc') as HTMLElement;const canvas=await captureElementCanvas(page,{scale:2,useCORS:true,backgroundColor:'#fff'});if(canvas.width<50||canvas.height<50)throw new Error('empty canvas');const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,210,297,'','FAST');pdf.save(`financial-declaration-${data.name||data.date}.pdf`)}finally{h.remove();cleanupExportArtifacts();}}
export async function downloadFinancialDeclarationWord(data:FinancialDeclarationData){const h=await host(data);try{const page=h.querySelector('.financial-declaration-doc') as HTMLElement|null;if(!page)throw new Error('تعذر العثور على قالب الإقرار');await downloadElementsAsDocx(`financial-declaration-${data.name||data.date}`,[page],'portrait')}finally{h.remove();cleanupExportArtifacts()}}
export async function printFinancialDeclaration(data:FinancialDeclarationData){try{await printHtmlDocument('سند إقرار والتزام',await embedded(data),financialDeclarationCss)}finally{/* print frame cleans itself */}}
