import { jsPDF } from 'jspdf';
import type { LabOrder, Language, Patient } from '../types';
import { captureElementCanvas, cleanupExportArtifacts, createSilentExportFrame } from './documentDownload';

const escapeHtml = (value: string | number | undefined) => String(value ?? '—')
  .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');

export async function downloadLabReport(order: LabOrder, patient: Patient, doctorName: string, language: Language) {
  if (!order.resultRows?.length) return;
  const isArabic = language === 'ar';
  const reportDate = new Date(order.completedAt || order.date).toLocaleDateString(isArabic ? 'ar-EG' : 'en-GB');
  const host = await createSilentExportFrame(`
    <section dir="${isArabic ? 'rtl' : 'ltr'}" style="width:794px;min-height:1123px;box-sizing:border-box;background:#fff;padding:42px;font-family:Arial,Tahoma,sans-serif;color:#102a43">
    <header style="display:flex;align-items:center;justify-content:space-between;border-bottom:4px solid #0f8f9b;padding-bottom:18px;margin-bottom:22px">
      <div><div style="font-size:12px;letter-spacing:2px;color:#0f8f9b;font-weight:800">WAFAA HOSPITAL</div><h1 style="margin:8px 0 0;font-size:28px;color:#113b56">${escapeHtml(order.serviceName || order.category)}</h1></div>
      <img src="${window.location.origin}/wafaa-hospital-logo.png" alt="Wafaa Hospital" style="width:88px;height:70px;object-fit:contain"/>
    </header>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px 24px;background:#eef8f8;border:1px solid #cfe8e9;border-radius:14px;padding:16px 18px;margin-bottom:24px;font-size:13px">
      <div>${isArabic?'اسم المريض':'Patient name'}: <strong>${escapeHtml(patient.fullName)}</strong></div>
      <div>${isArabic?'رقم الهوية':'National ID'}: <strong>${escapeHtml(patient.idNumber)}</strong></div>
      <div>${isArabic?'رقم التقرير':'Report number'}: <strong>${escapeHtml(order.reportNumber)}</strong></div>
      <div>${isArabic?'تاريخ الإصدار':'Issue date'}: <strong>${escapeHtml(reportDate)}</strong></div>
      <div style="grid-column:1/-1">${isArabic?'الطبيب الطالب':'Requested by'}: <strong>${escapeHtml(doctorName)}</strong></div>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px;direction:ltr">
      <thead><tr style="background:#123b54;color:#fff"><th style="padding:12px;border:1px solid #123b54;text-align:left">Test</th><th style="padding:12px;border:1px solid #123b54;text-align:center">Result</th><th style="padding:12px;border:1px solid #123b54;text-align:left">Reference Range</th></tr></thead>
      <tbody>${order.resultRows.map((row,index)=>`<tr style="background:${index%2?'#f7fafc':'#fff'}"><td style="padding:10px;border:1px solid #ccd9e0;font-weight:700">${escapeHtml(row.test)}</td><td style="padding:10px;border:1px solid #ccd9e0;text-align:center;font-weight:800;color:#087d86">${escapeHtml(row.result)}</td><td style="padding:10px;border:1px solid #ccd9e0">${escapeHtml(row.referenceRange)}</td></tr>`).join('')}</tbody>
    </table>
    ${order.notes?`<div style="margin-top:20px;padding:14px;border:1px solid #d9e5ea;border-radius:10px;font-size:13px"><strong>${isArabic?'ملاحظات':'Notes'}:</strong> ${escapeHtml(order.notes)}</div>`:''}
    <footer style="display:flex;justify-content:space-between;align-items:end;margin-top:42px;padding-top:16px;border-top:1px solid #d9e5ea;color:#5d7280;font-size:11px"><span>${isArabic?'نتيجة مخبرية إلكترونية معتمدة داخل نظام المستشفى':'Electronic laboratory result generated by the hospital system'}</span><span>© Wafaa Hospital</span></footer></section>`,794,1220);
  try {
    await new Promise(resolve => window.setTimeout(resolve, 120));
    const canvas = await captureElementCanvas(host,{scale:2,useCORS:true,backgroundColor:'#ffffff'});
    const pdf = new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});
    const width = 190; const height = canvas.height * width / canvas.width;
    pdf.addImage(canvas.toDataURL('image/png'),'PNG',10,10,width,Math.min(height,277),'','FAST');
    pdf.save(`${order.reportNumber || order.id}.pdf`);
  } finally { host.remove(); cleanupExportArtifacts(); }
}
