<?php

return [
    'catalog' => [
        ['key' => 'dashboard.view',       'module' => 'dashboard',       'action' => 'view',   'name_ar' => 'عرض لوحة القيادة',       'name_en' => 'View dashboard',          'financial' => false],
        ['key' => 'patients.view',        'module' => 'patients',        'action' => 'view',   'name_ar' => 'عرض المرضى',              'name_en' => 'View patients',           'financial' => false],
        ['key' => 'patients.create',      'module' => 'patients',        'action' => 'create', 'name_ar' => 'إضافة مريض',              'name_en' => 'Create patients',         'financial' => false],
        ['key' => 'patients.update',      'module' => 'patients',        'action' => 'update', 'name_ar' => 'تعديل بيانات المريض',     'name_en' => 'Update patients',         'financial' => false],
        ['key' => 'patients.delete',      'module' => 'patients',        'action' => 'delete', 'name_ar' => 'حذف المريض وملفه',        'name_en' => 'Delete patients',         'financial' => false],
        ['key' => 'patient_inquiries.view','module' => 'patient_inquiries','action' => 'view',   'name_ar' => 'عرض شاشة الاستعلامات',      'name_en' => 'View patient inquiries',   'financial' => false],
        ['key' => 'archive.view',        'module' => 'archive',        'action' => 'view',   'name_ar' => 'عرض أرشيف المرضى الخارجين', 'name_en' => 'View discharged patient archive', 'financial' => false],
        ['key' => 'archive.export',      'module' => 'archive',        'action' => 'export', 'name_ar' => 'تصدير أرشيف المرضى PDF',    'name_en' => 'Export discharged archive PDF', 'financial' => false],
        ['key' => 'visits.view',          'module' => 'visits',          'action' => 'view',   'name_ar' => 'عرض الزيارات',            'name_en' => 'View visits',             'financial' => false],
        ['key' => 'visits.create',        'module' => 'visits',          'action' => 'create', 'name_ar' => 'تسجيل زيارة',             'name_en' => 'Create visits',           'financial' => false],
        ['key' => 'visits.update',        'module' => 'visits',          'action' => 'update', 'name_ar' => 'تعديل حالة الزيارة',      'name_en' => 'Update visits',           'financial' => false],
        ['key' => 'queue.view',           'module' => 'queue',           'action' => 'view',   'name_ar' => 'عرض الطابور',             'name_en' => 'View queue',              'financial' => false],
        ['key' => 'queue.update',         'module' => 'queue',           'action' => 'update', 'name_ar' => 'إدارة الطابور',           'name_en' => 'Manage queue',            'financial' => false],
        ['key' => 'dental.view',          'module' => 'dental',          'action' => 'view',   'name_ar' => 'عرض عيادة الأسنان',        'name_en' => 'View Dental clinic',       'financial' => false],
        ['key' => 'dental.update',        'module' => 'dental',          'action' => 'update', 'name_ar' => 'تسجيل وتعديل خدمات الأسنان', 'name_en' => 'Manage Dental services',   'financial' => false],
        ['key' => 'dental.manage',        'module' => 'dental',          'action' => 'manage', 'name_ar' => 'إدارة أطباء وملفات الأسنان', 'name_en' => 'Administer Dental clinic', 'financial' => false],
        ['key' => 'dental.export',        'module' => 'dental',          'action' => 'export', 'name_ar' => 'تصدير إحصائيات الأسنان',     'name_en' => 'Export Dental statistics', 'financial' => true],
        ['key' => 'elderly.view',         'module' => 'elderly',         'action' => 'view',   'name_ar' => 'عرض قسم المسنين والمسنات',    'name_en' => 'View elderly care residents', 'financial' => false],
        ['key' => 'elderly.update',       'module' => 'elderly',         'action' => 'update', 'name_ar' => 'إدارة ملفات المسنين والمسنات', 'name_en' => 'Manage elderly care residents', 'financial' => false],
        ['key' => 'elderly.export',       'module' => 'elderly',         'action' => 'export', 'name_ar' => 'تصدير إحصائيات المسنين والمسنات', 'name_en' => 'Export elderly care statistics', 'financial' => false],
        ['key' => 'operations.view',     'module' => 'operations',     'action' => 'view',   'name_ar' => 'عرض واجهة العمليات',       'name_en' => 'View operations interface',       'financial' => false],
        ['key' => 'operations.create',   'module' => 'operations',     'action' => 'create', 'name_ar' => 'تسجيل حالة عمليات',       'name_en' => 'Create operation cases',          'financial' => false],
        ['key' => 'operations.print',    'module' => 'operations',     'action' => 'print',  'name_ar' => 'طباعة إذن دخول العمليات', 'name_en' => 'Print operation admission permit', 'financial' => false],
        ['key' => 'admissions.view',      'module' => 'admissions',      'action' => 'view',   'name_ar' => 'عرض المبيت',             'name_en' => 'View admissions',         'financial' => false],
        ['key' => 'admissions.create',    'module' => 'admissions',      'action' => 'create', 'name_ar' => 'إضافة حالة مبيت',        'name_en' => 'Create admissions',       'financial' => false],
        ['key' => 'admissions.update',    'module' => 'admissions',      'action' => 'update', 'name_ar' => 'تعديل وخروج المبيت',      'name_en' => 'Update/discharge',        'financial' => false],
        ['key' => 'inpatient_rehab.view', 'module' => 'inpatient_rehab', 'action' => 'view',   'name_ar' => 'عرض ملف التأهيل الطبي',   'name_en' => 'View inpatient rehab',    'financial' => false],
        ['key' => 'inpatient_rehab.update','module'=> 'inpatient_rehab', 'action' => 'update', 'name_ar' => 'إدارة ملف التأهيل الطبي', 'name_en' => 'Manage inpatient rehab',  'financial' => false],
        ['key' => 'inpatient_rehab.print','module' => 'inpatient_rehab', 'action' => 'print',  'name_ar' => 'طباعة تقارير التأهيل',    'name_en' => 'Print rehab reports',     'financial' => false],
        ['key' => 'inpatient_rehab.export','module'=> 'inpatient_rehab', 'action' => 'export', 'name_ar' => 'تصدير تقارير التأهيل',    'name_en' => 'Export rehab reports',    'financial' => false],
        ['key' => 'inpatient_social.view','module' => 'inpatient_social','action' => 'view',   'name_ar' => 'عرض الخدمة الاجتماعية والنفسية','name_en' => 'View social & psych service','financial' => false],
        ['key' => 'inpatient_social.update','module'=>'inpatient_social','action'=> 'update', 'name_ar' => 'تعبئة وحفظ دراسة الحالة', 'name_en' => 'Manage social assessments','financial' => false],
        ['key' => 'inpatient_social.print','module'=> 'inpatient_social','action' => 'print',  'name_ar' => 'طباعة دراسة الحالة',      'name_en' => 'Print social assessments','financial' => false],
        ['key' => 'inpatient_social.export','module'=>'inpatient_social','action'=> 'export', 'name_ar' => 'تصدير دراسة الحالة',      'name_en' => 'Export social assessments','financial' => false],
        ['key' => 'inpatient_pt.view',    'module' => 'inpatient_pt',    'action' => 'view',   'name_ar' => 'عرض العلاج الطبيعي الداخلي', 'name_en' => 'View internal physical therapy','financial' => false],
        ['key' => 'inpatient_pt.update',  'module' => 'inpatient_pt',    'action' => 'update', 'name_ar' => 'توزيع ومتابعة جلسات العلاج الطبيعي الداخلي', 'name_en' => 'Manage internal PT assignments','financial' => false],
        ['key' => 'inpatient_pt.print',   'module' => 'inpatient_pt',    'action' => 'print',  'name_ar' => 'طباعة تقارير العلاج الطبيعي الداخلي', 'name_en' => 'Print internal PT reports','financial' => false],
        ['key' => 'inpatient_pt.export',  'module' => 'inpatient_pt',    'action' => 'export', 'name_ar' => 'تصدير تقارير العلاج الطبيعي الداخلي', 'name_en' => 'Export internal PT reports','financial' => false],
        ['key' => 'outpatient_pt.view',   'module' => 'outpatient_pt',   'action' => 'view',   'name_ar' => 'عرض العلاج الطبيعي الخارجي', 'name_en' => 'View outpatient physical therapy','financial' => false],
        ['key' => 'outpatient_pt.update', 'module' => 'outpatient_pt',   'action' => 'update', 'name_ar' => 'إدارة التسجيل والحالات والجلسات للعلاج الطبيعي الخارجي', 'name_en' => 'Manage outpatient PT cases and sessions','financial' => false],
        ['key' => 'outpatient_pt.print',  'module' => 'outpatient_pt',   'action' => 'print',  'name_ar' => 'طباعة تقارير العلاج الطبيعي الخارجي', 'name_en' => 'Print outpatient PT reports','financial' => false],
        ['key' => 'outpatient_pt.export', 'module' => 'outpatient_pt',   'action' => 'export', 'name_ar' => 'تصدير تقارير العلاج الطبيعي الخارجي', 'name_en' => 'Export outpatient PT reports','financial' => false],
        ['key' => 'inpatient_finance.view','module'=> 'inpatient_finance','action'=> 'view',  'name_ar' => 'عرض مالية المبيت',        'name_en' => 'View inpatient finance',  'financial' => true],
        ['key' => 'inpatient_finance.update','module'=>'inpatient_finance','action'=>'update','name_ar'=>'إدارة حركات التغطية والمطالبات','name_en'=>'Manage inpatient finance','financial'=>true],
        ['key' => 'inpatient_finance.print','module'=>'inpatient_finance','action'=>'print', 'name_ar'=>'طباعة مطالبات وتقارير المبيت','name_en'=>'Print inpatient finance','financial'=>true],
        ['key' => 'inpatient_finance.export','module'=>'inpatient_finance','action'=>'export','name_ar'=>'تصدير مطالبات وتقارير المبيت','name_en'=>'Export inpatient finance','financial'=>true],
        ['key' => 'moh_portal.view',      'module' => 'moh_portal',      'action' => 'view',   'name_ar' => 'عرض بوابة وزارة الصحة',   'name_en' => 'View MOH portal',         'financial' => false],
        ['key' => 'moh_portal.create',    'module' => 'moh_portal',      'action' => 'create', 'name_ar' => 'إضافة مرضى وقائمة انتظار للوزارة','name_en' => 'Add MOH patients/waiting','financial' => false],
        ['key' => 'moh_portal.update',    'module' => 'moh_portal',      'action' => 'update', 'name_ar' => 'إدارة قوائم وزارة الصحة', 'name_en' => 'Manage MOH portal',       'financial' => false],
        ['key' => 'moh_portal.print',     'module' => 'moh_portal',      'action' => 'print',  'name_ar' => 'طباعة تقارير وزارة الصحة','name_en' => 'Print MOH reports',        'financial' => false],
        ['key' => 'moh_portal.export',    'module' => 'moh_portal',      'action' => 'export', 'name_ar' => 'تصدير تقارير وزارة الصحة','name_en' => 'Export MOH reports',      'financial' => false],
        ['key' => 'diagnostics.view',     'module' => 'diagnostics',     'action' => 'view',   'name_ar' => 'عرض التشخيص والفحوصات',   'name_en' => 'View diagnostics',        'financial' => false],
        ['key' => 'diagnostics.create',   'module' => 'diagnostics',     'action' => 'create', 'name_ar' => 'إضافة فحص أو صورة',       'name_en' => 'Create diagnostics',      'financial' => false],
        ['key' => 'diagnostics.update',   'module' => 'diagnostics',     'action' => 'update', 'name_ar' => 'تعديل نتائج الفحوصات',    'name_en' => 'Update diagnostics',      'financial' => false],
        ['key' => 'laboratory.view',      'module' => 'laboratory',      'action' => 'view',   'name_ar' => 'عرض بوابة المختبر',       'name_en' => 'View laboratory portal',  'financial' => false],
        ['key' => 'laboratory.update',    'module' => 'laboratory',      'action' => 'update', 'name_ar' => 'إدخال واعتماد النتائج',   'name_en' => 'Enter and approve results','financial' => false],
        ['key' => 'diagnostic_catalog.view',  'module'=>'diagnostic_catalog','action'=>'view',   'name_ar'=>'عرض دليل الفحوصات والأشعة', 'name_en'=>'View diagnostic catalog',   'financial'=>false],
        ['key' => 'diagnostic_catalog.create','module'=>'diagnostic_catalog','action'=>'create', 'name_ar'=>'إضافة نوع فحص أو أشعة',      'name_en'=>'Create diagnostic services','financial'=>false],
        ['key' => 'diagnostic_catalog.update','module'=>'diagnostic_catalog','action'=>'update', 'name_ar'=>'تعديل أنواع الفحوصات والأشعة','name_en'=>'Update diagnostic services','financial'=>false],
        ['key' => 'diagnostic_catalog.delete','module'=>'diagnostic_catalog','action'=>'delete', 'name_ar'=>'حذف أنواع الفحوصات والأشعة', 'name_en'=>'Delete diagnostic services','financial'=>false],
        ['key' => 'diagnostic_catalog.manage','module'=>'diagnostic_catalog','action'=>'fee',    'name_ar'=>'تعديل أسعار الفحوصات والأشعة','name_en'=>'Manage diagnostic prices',  'financial'=>true],
        ['key' => 'cashier_payment.view',     'module' => 'cashier_payment',    'action' => 'view',   'name_ar' => 'عرض شاشة التطبيق والتحصيل البنكي', 'name_en' => 'View payment & bank collection', 'financial' => true],
        ['key' => 'cashier_payment.update',   'module' => 'cashier_payment',    'action' => 'update', 'name_ar' => 'اعتماد بيانات الدفع والتحويل',     'name_en' => 'Approve payment details',        'financial' => true],
        ['key' => 'cashier_payment.export',   'module' => 'cashier_payment',    'action' => 'export', 'name_ar' => 'تصدير كشف التحصيل اليومي Excel',   'name_en' => 'Export daily payment sheet',     'financial' => true],
        ['key' => 'cashier_collection.view',  'module' => 'cashier_collection', 'action' => 'view',   'name_ar' => 'عرض شاشة المحصل المالي',           'name_en' => 'View financial collector desk',  'financial' => true],
        ['key' => 'cashier_collection.update','module' => 'cashier_collection', 'action' => 'update', 'name_ar' => 'اعتماد التحصيل وتحويله للتدقيق',   'name_en' => 'Approve collection',              'financial' => true],
        ['key' => 'cashier_collection.print', 'module' => 'cashier_collection', 'action' => 'print',  'name_ar' => 'طباعة إيصال وتذكرة الدور',         'name_en' => 'Print receipt and queue ticket',  'financial' => true],
        ['key' => 'cashier_collection.export','module' => 'cashier_collection', 'action' => 'export', 'name_ar' => 'تصدير كشف الإيرادات اليومية PDF', 'name_en' => 'Export daily revenue PDF',         'financial' => true],
        ['key' => 'financial_audit.view',     'module' => 'financial_audit',    'action' => 'view',   'name_ar' => 'عرض شاشة المدقق المالي',           'name_en' => 'View financial auditor desk',     'financial' => true],
        ['key' => 'financial_audit.update',   'module' => 'financial_audit',    'action' => 'update', 'name_ar' => 'تعديل واعتماد السجلات المالية',    'name_en' => 'Edit and audit finance records',  'financial' => true],
        ['key' => 'financial_audit.create',   'module' => 'financial_audit',    'action' => 'create', 'name_ar' => 'إضافة سجل مالي يدوي',             'name_en' => 'Create manual finance record',    'financial' => true],
        ['key' => 'financial_audit.delete',   'module' => 'financial_audit',    'action' => 'delete', 'name_ar' => 'حذف سجل مالي',                    'name_en' => 'Delete finance record',           'financial' => true],
        ['key' => 'financial_audit.export',   'module' => 'financial_audit',    'action' => 'export', 'name_ar' => 'تصدير التدقيق المالي Excel',       'name_en' => 'Export financial audit Excel',    'financial' => true],
        ['key' => 'billing.create',       'module' => 'billing',         'action' => 'create', 'name_ar' => 'إصدار فاتورة وإيداع',     'name_en' => 'Issue invoices',          'financial' => true],
        ['key' => 'billing.view',         'module' => 'billing',         'action' => 'view',   'name_ar' => 'عرض جميع الفواتير',       'name_en' => 'View all invoices',       'financial' => true],
        ['key' => 'patient_finance.view', 'module' => 'patient_finance', 'action' => 'view',   'name_ar' => 'عرض الملف المالي للمريض', 'name_en' => 'View patient finance',     'financial' => true],
        ['key' => 'patient_finance.update','module'=> 'patient_finance', 'action' => 'update', 'name_ar' => 'تعديل حساب المريض',       'name_en' => 'Update patient finance',  'financial' => true],
        ['key' => 'transfers.view',       'module' => 'transfers',       'action' => 'view',   'name_ar' => 'عرض الحوالات المالية',    'name_en' => 'View transfers',          'financial' => true],
        ['key' => 'doctors.view',         'module' => 'doctors',         'action' => 'view',   'name_ar' => 'عرض الأطباء',             'name_en' => 'View doctors',            'financial' => false],
        ['key' => 'doctors.create',       'module' => 'doctors',         'action' => 'create', 'name_ar' => 'إضافة طبيب',              'name_en' => 'Create doctors',          'financial' => false],
        ['key' => 'doctors.update',       'module' => 'doctors',         'action' => 'update', 'name_ar' => 'تعديل طبيب',              'name_en' => 'Update doctors',          'financial' => false],
        ['key' => 'doctors.delete',       'module' => 'doctors',         'action' => 'delete', 'name_ar' => 'إزالة طبيب',              'name_en' => 'Remove doctors',          'financial' => false],
        ['key' => 'clinics.view',         'module' => 'clinics',         'action' => 'view',   'name_ar' => 'عرض العيادات',            'name_en' => 'View clinics',            'financial' => false],
        ['key' => 'clinics.create',       'module' => 'clinics',         'action' => 'create', 'name_ar' => 'إضافة عيادة',             'name_en' => 'Create clinics',          'financial' => false],
        ['key' => 'clinics.update',       'module' => 'clinics',         'action' => 'update', 'name_ar' => 'تعديل عيادة',             'name_en' => 'Update clinics',          'financial' => false],
        ['key' => 'clinics.delete',       'module' => 'clinics',         'action' => 'delete', 'name_ar' => 'إزالة عيادة',             'name_en' => 'Remove clinics',          'financial' => false],
        ['key' => 'clinics.fee_update',   'module' => 'clinics',         'action' => 'fee',    'name_ar' => 'تعديل رسوم الزيارات',     'name_en' => 'Update visit fees',       'financial' => true],
        ['key' => 'reports.view',         'module' => 'reports',         'action' => 'view',   'name_ar' => 'عرض تقارير المرضى',       'name_en' => 'View patient reports',    'financial' => false],
        ['key' => 'reports.print',        'module' => 'reports',         'action' => 'print',  'name_ar' => 'طباعة التقارير',          'name_en' => 'Print reports',           'financial' => false],
        ['key' => 'reports.export',       'module' => 'reports',         'action' => 'export', 'name_ar' => 'تصدير التقارير',          'name_en' => 'Export reports',          'financial' => false],
        ['key' => 'sponsors.manage',      'module' => 'reports',         'action' => 'update', 'name_ar' => 'إدارة جهات التغطية',      'name_en' => 'Manage sponsors',         'financial' => false],
        ['key' => 'settings.view',        'module' => 'settings',        'action' => 'view',   'name_ar' => 'عرض الإعدادات',           'name_en' => 'View settings',           'financial' => false],
        ['key' => 'settings.update',      'module' => 'settings',        'action' => 'update', 'name_ar' => 'تعديل إعدادات النظام',    'name_en' => 'Update settings',         'financial' => false],
        ['key' => 'users.view',           'module' => 'users',           'action' => 'view',   'name_ar' => 'عرض المستخدمين',          'name_en' => 'View users',              'financial' => false],
        ['key' => 'users.create',         'module' => 'users',           'action' => 'create', 'name_ar' => 'إضافة مستخدم',            'name_en' => 'Create users',            'financial' => false],
        ['key' => 'users.update',         'module' => 'users',           'action' => 'update', 'name_ar' => 'تعديل مستخدم وصلاحياته',  'name_en' => 'Update users',            'financial' => false],
        ['key' => 'users.delete',         'module' => 'users',           'action' => 'delete', 'name_ar' => 'تعطيل أو حذف مستخدم',    'name_en' => 'Disable/delete users',    'financial' => false],
        ['key' => 'finance.view',         'module' => 'finance',         'action' => 'view',   'name_ar' => 'عرض التقارير المالية',    'name_en' => 'View financial reports',  'financial' => true],
        ['key' => 'finance.print',        'module' => 'finance',         'action' => 'print',  'name_ar' => 'طباعة التقارير المالية',  'name_en' => 'Print financial reports', 'financial' => true],
        ['key' => 'finance.export',       'module' => 'finance',         'action' => 'export', 'name_ar' => 'تصدير التقارير المالية',  'name_en' => 'Export financial reports','financial' => true],
        ['key' => 'engineer_activity.view','module' => 'engineer_activity','action' => 'view',  'name_ar' => 'عرض شاشة نشاط المستخدمين', 'name_en' => 'View user activity monitor','financial' => false],
        ['key' => 'trash_bin.view',       'module' => 'trash_bin',       'action' => 'view',   'name_ar' => 'عرض سلة المحذوفات الخاصة', 'name_en' => 'View private trash bin',   'financial' => false],
        ['key' => 'trash_bin.restore',    'module' => 'trash_bin',       'action' => 'update', 'name_ar' => 'استعادة عناصر المحذوفات',   'name_en' => 'Restore deleted items',    'financial' => false],
        ['key' => 'doctor_portal.view',   'module' => 'doctor_portal',   'action' => 'view',   'name_ar' => 'عرض بوابة الطبيب',        'name_en' => 'View doctor portal',      'financial' => false],
        ['key' => 'doctor_portal.update', 'module' => 'doctor_portal',   'action' => 'update', 'name_ar' => 'إدارة الحالات والملاحظات','name_en' => 'Manage clinical cases',    'financial' => false],
    ],

    'role_defaults' => [
        'admin' => ['dashboard.view','patient_inquiries.view','archive.view','archive.export','patients.view','patients.create','patients.update','patients.delete','visits.view','visits.create','visits.update','queue.view','queue.update','dental.view','dental.update','dental.manage','dental.export','elderly.view','elderly.update','elderly.export','operations.view','operations.create','operations.print','admissions.view','admissions.create','admissions.update','inpatient_rehab.view','inpatient_rehab.update','inpatient_rehab.print','inpatient_rehab.export','inpatient_social.view','inpatient_social.update','inpatient_social.print','inpatient_social.export','inpatient_pt.view','inpatient_pt.update','inpatient_pt.print','inpatient_pt.export','outpatient_pt.view','outpatient_pt.update','outpatient_pt.print','outpatient_pt.export','diagnostics.view','diagnostics.create','diagnostics.update','laboratory.view','laboratory.update','diagnostic_catalog.view','diagnostic_catalog.create','diagnostic_catalog.update','diagnostic_catalog.delete','doctors.view','doctors.create','doctors.update','doctors.delete','clinics.view','clinics.create','clinics.update','clinics.delete','reports.view','reports.print','reports.export','sponsors.manage','settings.view','settings.update','users.view','users.create','users.update','users.delete'],
        'cashier' => ['patients.create','visits.create','clinics.view','doctors.view','dental.view','dental.update'],
        'payment_auditor' => ['cashier_payment.view','cashier_payment.update','cashier_payment.export'],
        'financial_collector' => ['cashier_collection.view','cashier_collection.update','cashier_collection.print','cashier_collection.export'],
        'financial_auditor' => ['financial_audit.view','financial_audit.update','financial_audit.create','financial_audit.delete','financial_audit.export','dental.view','dental.export'],
        'inquiry_clerk' => ['patient_inquiries.view'],
        'archive_clerk' => ['archive.view','archive.export'],
        'it_head' => ['@nonfinancial'],
        'treasurer' => ['*'],
        'doctor' => ['doctor_portal.view','doctor_portal.update','queue.update','diagnostics.view','diagnostics.create','diagnostics.update'],
        'lab_technician' => ['laboratory.view','laboratory.update','diagnostics.view','diagnostics.create','diagnostics.update','diagnostic_catalog.view','diagnostic_catalog.create','diagnostic_catalog.update','diagnostic_catalog.delete','diagnostic_catalog.manage'],
        'receptionist' => ['patients.view','patients.create','patients.update','visits.view','visits.create','visits.update','queue.view','clinics.view','doctors.view','dental.view','dental.update'],
        'inpatient_manager' => ['dashboard.view','archive.view','archive.export','patients.view','patients.update','visits.view','queue.view','queue.update','operations.view','operations.create','operations.print','admissions.view','admissions.create','admissions.update','inpatient_rehab.view','inpatient_rehab.update','inpatient_rehab.print','inpatient_rehab.export','inpatient_social.view','inpatient_social.update','inpatient_social.print','inpatient_social.export','inpatient_pt.view','inpatient_pt.update','inpatient_pt.print','inpatient_pt.export','reports.view','reports.print','reports.export'],
        'elderly_care_manager' => ['elderly.view','elderly.update','elderly.export','patients.view','patient_inquiries.view'],
        'rehab_specialist' => ['inpatient_rehab.view','inpatient_rehab.update','inpatient_rehab.print','inpatient_rehab.export'],
        'social_worker' => ['inpatient_social.view','inpatient_social.update','inpatient_social.print','inpatient_social.export'],
        'inpatient_pt' => ['inpatient_pt.view','inpatient_pt.update','inpatient_pt.print','inpatient_pt.export'],
        'outpatient_pt' => ['outpatient_pt.view','outpatient_pt.update','outpatient_pt.print','outpatient_pt.export'],
        'pt_head' => ['outpatient_pt.view','outpatient_pt.update','outpatient_pt.print','outpatient_pt.export','inpatient_pt.view','inpatient_pt.update','inpatient_pt.print','inpatient_pt.export'],
        'inpatient_finance' => ['inpatient_finance.view','inpatient_finance.update','inpatient_finance.print','inpatient_finance.export'],
        'moh_user' => ['moh_portal.view','moh_portal.create','moh_portal.update','moh_portal.print','moh_portal.export'],
        'operations_clerk' => ['operations.view','operations.create','operations.print'],
        'custom' => [],
    ],
];
