<?php
namespace Tests\Feature;
use App\Models\{Clinic,DiagnosticService,Doctor,LabOrder,Patient,User};
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;
class HospitalWorkflowTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(DatabaseSeeder::class);$user=User::create(['username'=>'DOC-TEST','display_name'=>'Test Doctor','password'=>'Doctor@2026','role'=>'doctor','active'=>true]);$doctor=Doctor::create(['user_id'=>$user->id,'staff_id'=>'DOC-TEST','name'=>'Test Doctor','specialty'=>'General','active'=>true]);$doctor->clinics()->attach(Clinic::firstOrFail());}
 public function test_cashier_can_credit_wallet_and_register_visit():void{$cashier=User::where('username','cashier')->firstOrFail();Sanctum::actingAs($cashier);$patient=Patient::firstOrFail();$clinic=Clinic::where('key','general')->firstOrFail();$doctor=Doctor::firstOrFail();$before=(float)$patient->wallet_balance;$this->postJson('/api/v1/invoices',['patient_id'=>$patient->id,'service'=>'دفعة اختبار','unit_price'=>50,'coverage_ratio'=>0,'payment_method'=>'cash'])->assertCreated();$this->postJson('/api/v1/visits',['patient_id'=>$patient->id,'clinic_id'=>$clinic->id,'doctor_id'=>$doctor->id,'visit_date'=>today(),'notes'=>''])->assertCreated()->assertJsonPath('data.queueNumber',1);$this->assertEquals($before+50-(float)$clinic->visit_fee,(float)$patient->fresh()->wallet_balance);}
 public function test_doctor_finish_creates_follow_up_after_seven_days():void{$cashier=User::where('username','cashier')->firstOrFail();Sanctum::actingAs($cashier);$patient=Patient::firstOrFail();$clinic=Clinic::where('key','general')->firstOrFail();$doctor=Doctor::firstOrFail();$visitId=$this->postJson('/api/v1/visits',['patient_id'=>$patient->id,'clinic_id'=>$clinic->id,'doctor_id'=>$doctor->id,'visit_date'=>today()])->json('data.id');Sanctum::actingAs($doctor->user);$this->postJson("/api/v1/visits/$visitId/finish")->assertOk()->assertJsonPath('data.followUpDate',now()->addDays(7)->format('Y-m-d'));$this->assertDatabaseHas('follow_up_appointments',['source_visit_id'=>$visitId,'appointment_date'=>now()->addDays(7)->format('Y-m-d'),'status'=>'scheduled']);}
 public function test_admin_cannot_open_financial_ledger_but_treasurer_can():void{$patient=Patient::firstOrFail();Sanctum::actingAs(User::where('username','Dr.Fouad_Najm')->firstOrFail());$this->getJson("/api/v1/patients/$patient->id/ledger")->assertForbidden();Sanctum::actingAs(User::where('username','Eng.Mohammed_Moqbil')->firstOrFail());$this->getJson("/api/v1/patients/$patient->id/ledger")->assertOk();}
 public function test_admin_is_read_only_and_cashier_cannot_open_finance_reports():void{Sanctum::actingAs(User::where('username','Dr.Fouad_Najm')->firstOrFail());$this->postJson('/api/v1/admissions',[])->assertForbidden();Sanctum::actingAs(User::where('username','cashier')->firstOrFail());$this->getJson('/api/v1/reports/finance')->assertForbidden();}
 public function test_it_head_can_create_a_database_user_with_custom_page_permissions():void{$it=User::where('username','Eng.Ahmed_Jaber')->firstOrFail();Sanctum::actingAs($it);$response=$this->postJson('/api/v1/users',['username'=>'records.user','display_name'=>'Records User','password'=>'Records@2026','password_confirmation'=>'Records@2026','role'=>'cashier','active'=>true,'permissions'=>['patients.view']])->assertCreated()->assertJsonPath('data.permissions.0','patients.view');$created=User::findOrFail($response->json('data.id'));Sanctum::actingAs($created);$this->getJson('/api/v1/patients')->assertOk();$this->getJson('/api/v1/dashboard')->assertForbidden();}
 public function test_it_head_cannot_grant_financial_permissions():void{Sanctum::actingAs(User::where('username','Eng.Ahmed_Jaber')->firstOrFail());$this->postJson('/api/v1/users',['username'=>'finance.user','display_name'=>'Finance User','password'=>'Finance@2026','password_confirmation'=>'Finance@2026','role'=>'cashier','permissions'=>['finance.view']])->assertForbidden();}
 public function test_it_head_cannot_create_update_or_delete_treasurer_accounts():void{$it=User::where('username','Eng.Ahmed_Jaber')->firstOrFail();$treasurer=User::where('username','Eng.Mohammed_Moqbil')->firstOrFail();Sanctum::actingAs($it);$this->postJson('/api/v1/users',['username'=>'assistant.treasurer','display_name'=>'Assistant Treasurer','password'=>'Treasury@2026','password_confirmation'=>'Treasury@2026','role'=>'treasurer','permissions'=>[]])->assertForbidden();$this->patchJson("/api/v1/users/$treasurer->id",['display_name'=>'Changed'])->assertForbidden();$this->deleteJson("/api/v1/users/$treasurer->id")->assertForbidden();}
 public function test_cashier_orders_lab_test_only_when_wallet_is_sufficient():void{$cashier=User::where('username','cashier')->firstOrFail();$service=DiagnosticService::where('type','lab')->firstOrFail();$funded=Patient::orderByDesc('wallet_balance')->firstOrFail();$empty=Patient::orderBy('wallet_balance')->firstOrFail();Sanctum::actingAs($cashier);$before=(float)$funded->wallet_balance;$this->postJson('/api/v1/diagnostics/labs',['patient_id'=>$funded->id,'diagnostic_service_id'=>$service->id])->assertCreated();$this->assertEquals($before-(float)$service->price,(float)$funded->fresh()->wallet_balance);$this->postJson('/api/v1/diagnostics/labs',['patient_id'=>$empty->id,'diagnostic_service_id'=>$service->id])->assertUnprocessable();}
 public function test_laboratory_employee_completes_result_rows():void{$cashier=User::where('username','cashier')->firstOrFail();$service=DiagnosticService::where('type','lab')->firstOrFail();$patient=Patient::orderByDesc('wallet_balance')->firstOrFail();Sanctum::actingAs($cashier);$id=$this->postJson('/api/v1/diagnostics/labs',['patient_id'=>$patient->id,'diagnostic_service_id'=>$service->id])->assertCreated()->json('data.id');Sanctum::actingAs(User::where('username','laboratory')->firstOrFail());$this->postJson("/api/v1/diagnostics/labs/$id/complete",['result_rows'=>[['test'=>'F.B.S','result'=>'96','reference_range'=>'70 - 110 mg/dL']],'notes'=>'Approved'])->assertOk()->assertJsonPath('data.status','done');$this->assertNotNull(LabOrder::findOrFail($id)->report_number);}
 public function test_deleted_user_is_permanently_removed_from_database_and_list():void{$treasurer=User::where('username','Eng.Mohammed_Moqbil')->firstOrFail();$target=User::create(['username'=>'temporary.user','display_name'=>'Temporary User','password'=>'Temporary@2026','role'=>'cashier','active'=>true]);Sanctum::actingAs($treasurer);$this->deleteJson("/api/v1/users/$target->id")->assertOk();$this->assertDatabaseMissing('users',['id'=>$target->id]);$this->getJson('/api/v1/users')->assertOk()->assertJsonMissing(['username'=>'temporary.user']);}

 public function test_inpatient_manager_account_is_seeded_with_inpatient_access():void{$user=User::where('username','inpatient')->firstOrFail();$this->assertSame('inpatient_manager',$user->role);$this->assertContains('admissions.view',$user->effectivePermissionKeys());$this->assertContains('admissions.update',$user->effectivePermissionKeys());}
 public function test_treasurer_can_create_user_with_a_free_text_role():void{Sanctum::actingAs(User::where('username','Eng.Mohammed_Moqbil')->firstOrFail());$this->postJson('/api/v1/users',['username'=>'custom.role.user','display_name'=>'Custom Role User','password'=>'CustomRole@2026','password_confirmation'=>'CustomRole@2026','role'=>'ممرض المبيت الليلي','permissions'=>['admissions.view']])->assertCreated()->assertJsonPath('data.role','ممرض المبيت الليلي');$this->assertDatabaseHas('users',['username'=>'custom.role.user','role'=>'ممرض المبيت الليلي']);}
}
